### ISSUE TITLE
Rename .js containing JSX as .jsx for build systems

### ISSUE THREAD

**Issue by RaitoBezarius** [mwri/cytoscape-react#1]
Hi there, thank you for your package.

It seems like some JavaScript files contains JSX and this is breaking some build systems assuming the contents based on the extension.

Would it be possible to rename some JS into JSX? I can send some PR if needed.

Thanks again!

**Comment by mwri** [comment]
Hey. Sorry for the delay. I don't see why not. What does it break?

**Comment by mwri** [comment]
@RaitoBezarius I'd have accepted your PR, but, tis the work of a moment, I renamed the files for you, as I can't see the harm, and it doesn't seem to break anything of mine. I've released it as 2.0.0 though, as though I don't imagine it'll cause any problems, I'm not sure I have any way to know for sure. It's an odd one. I'd still be interested to hear what the js extensions broke though?

**Comment by RaitoBezarius** [comment]
@mwri As you can see, some builders like `esbuild` enable JSX transformers only for `*.{jsx,tsx}` by default (it is also an optimization based on the filename): https://esbuild.github.io/content-types/#jsx ; if you were using a project which enabled JSX transforms only for these extensions, installing this dependency broke your building system.

Closing this issue makes the initial installation process for end users friendlier and works "out of the box" as long as ~sane build systems are used.

Anyway, thank you for your release!

**Comment by mwri** [comment]
@RaitoBezarius I see, yes fair enough, you're welcome, sorry it took me a while to reply, I clearly missed an email somewhere a couple of weeks ago.

**Comment by RaitoBezarius** [comment]
@mwri No worries! I have multiple suggestions in respect to your project, so I might come back in your issues soon ;)
